/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: .sanity/schema.json
export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo?: AccessibleImage;
  website?: string;
  description?: string;
  displayOrder?: number;
  active?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AccessibleImage = {
  _type: "accessibleImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  decorative?: boolean;
  alt?: string;
  caption?: string;
  credit?: string;
};

export type GoverningBody = {
  _id: string;
  _type: "governingBody";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  bodyType: "command" | "governingBody";
  title: string;
  mandateStart?: string;
  mandateEnd?: string;
  description?: PortableText;
  roles: Array<
    {
      _key: string;
    } & GoverningRole
  >;
};

export type InstitutionalDocumentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "institutionalDocument";
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & AccessibleImage)
  | ({
      _key: string;
    } & InstitutionalDocumentReference)
>;

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type InstitutionalDocument = {
  _id: string;
  _type: "institutionalDocument";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  category:
    "statutes" | "reports" | "accounts" | "regulations" | "minutes" | "other";
  file: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  date?: string;
  reference?: string;
  accessibleSummary: PortableText;
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  date?: string;
  description?: PortableText;
  coverImage: AccessibleImage;
  items: Array<
    {
      _key: string;
    } & GalleryItem
  >;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  openGraphImage?: AccessibleImage;
  noIndex?: boolean;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Training = {
  _id: string;
  _type: "training";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  description: PortableText;
  startDate?: string;
  endDate?: string;
  location?: string;
  audience?: string;
  enrollmentInformation?: PortableText;
  status: "planned" | "open" | "closed" | "completed" | "cancelled";
  seo?: Seo;
};

export type TrainingInformation = {
  _id: string;
  _type: "trainingInformation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  introduction: PortableText;
  body?: PortableText;
  seo?: Seo;
};

export type Vehicle = {
  _id: string;
  _type: "vehicle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  designation: string;
  category: "ambulance" | "firefighting" | "command" | "support" | "other";
  otherCategory?: string;
  mainImage?: AccessibleImage;
  publicDescription?: PortableText;
  publicSpecifications?: Array<{
    label: string;
    value: string;
    _type: "publicSpecification";
    _key: string;
  }>;
  specificationsApprovedForPublication?: boolean;
  gallery?: Array<
    {
      _key: string;
    } & GalleryItem
  >;
  displayOrder?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  visualType: "image" | "icon";
  image?: AccessibleImage;
  icon?:
    | "emergency"
    | "transport"
    | "prevention"
    | "training"
    | "community"
    | "general";
  content: PortableText;
  availabilityInformation?: PortableText;
  contactChannels?: Array<
    {
      _key: string;
    } & ContactChannel
  >;
  displayOrder?: number;
  seo?: Seo;
};

export type NewsCategory = {
  _id: string;
  _type: "newsCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
};

export type NewsCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "newsCategory";
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type NewsArticle = {
  _id: string;
  _type: "newsArticle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage?: AccessibleImage;
  fallbackVisual?:
    | "vehicle"
    | "fire"
    | "community"
    | "transport"
    | "training"
    | "institutional"
    | "general";
  body: PortableText;
  publicationDate: string;
  categories: Array<
    {
      _key: string;
    } & NewsCategoryReference
  >;
  author?: PersonReference;
  seo?: Seo;
};

export type InstitutionalPage = {
  _id: string;
  _type: "institutionalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  introduction?: string;
  featuredImage?: AccessibleImage;
  body: PortableText;
  documents?: Array<
    {
      _key: string;
    } & InstitutionalDocumentReference
  >;
  seo?: Seo;
};

export type ContactInformation = {
  _id: string;
  _type: "contactInformation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  informationConfirmedForPublication?: boolean;
  address?: Address;
  generalEmail?: string;
  telephone?: string;
  additionalChannels?: Array<
    {
      _key: string;
    } & ContactChannel
  >;
  contactHours?: PortableText;
  directionsMapUrl?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  emergencyWarning: string;
  seo?: Seo;
};

export type Address = {
  _type: "address";
  line1: string;
  line2?: string;
  postalCode?: string;
  locality?: string;
  municipality?: string;
  country?: string;
};

export type DonationInformation = {
  _id: string;
  _type: "donationInformation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  introduction: PortableText;
  waysToContribute?: PortableText;
  donationMethods?: Array<
    {
      _key: string;
    } & DonationMethod
  >;
  seo?: Seo;
};

export type MembershipInformation = {
  _id: string;
  _type: "membershipInformation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  introduction: PortableText;
  eligibility?: PortableText;
  benefits?: Array<string>;
  process?: Array<{
    title: string;
    description?: string;
    _type: "membershipStep";
    _key: string;
  }>;
  fees?: PortableText;
  feesConfirmedForPublication?: boolean;
  feesConfirmationDate?: string;
  faq?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  futureFormIntroduction?: PortableText;
  seo?: Seo;
};

export type RecruitmentInformation = {
  _id: string;
  _type: "recruitmentInformation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  introduction: PortableText;
  eligibility?: PortableText;
  requirements?: Array<string>;
  stages?: Array<{
    title: string;
    description?: string;
    _type: "recruitmentStage";
    _key: string;
  }>;
  expectations?: PortableText;
  faq?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  futureFormIntroduction?: PortableText;
  privacySummary?: PortableText;
  seo?: Seo;
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    headline: string;
    highlightedFragment?: string;
    description?: string;
    image?: AccessibleImage;
    emergencyCta?: CallToAction;
    recruitmentCta?: CallToAction;
    supportCta?: CallToAction;
  };
  statistics?: Array<
    {
      _key: string;
    } & Statistic
  >;
  mission?: {
    sectionLabel?: string;
    title?: string;
    body?: PortableText;
    image?: AccessibleImage;
  };
  featuredServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  latestNews?: {
    sectionLabel?: string;
    title?: string;
    itemCount?: number;
  };
  supportSection?: {
    sectionLabel?: string;
    title?: string;
    description?: string;
    cta?: CallToAction;
  };
  seo?: Seo;
};

export type CallToAction = {
  _type: "callToAction";
  label: string;
  accessibleLabel?: string;
  destinationType: "internal" | "external" | "telephone";
  internalPath?: string;
  externalUrl?: string;
  phoneNumber?: string;
  style: "primary" | "secondary" | "emergency";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  officialName: string;
  shortName?: string;
  institutionalDescription?: string;
  logo?: AccessibleImage;
  siteUrl?: string;
  defaultSeo?: Seo;
};

export type FaqItem = {
  _type: "faqItem";
  question: string;
  answer: PortableText;
};

export type GalleryItem = {
  _type: "galleryItem";
  image: AccessibleImage;
};

export type GoverningRole = {
  _type: "governingRole";
  roleTitle: string;
  person: PersonReference;
  publicNote?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  publicName: string;
  photograph?: AccessibleImage;
  biography?: PortableText;
  publicContactChannels?: Array<
    {
      _key: string;
    } & ContactChannel
  >;
};

export type DonationMethod = {
  _type: "donationMethod";
  methodType: "bankTransfer" | "mbWay" | "external" | "inPerson" | "other";
  title: string;
  description?: PortableText;
  iban?: string;
  mbWayNumber?: string;
  externalUrl?: string;
  confirmedForPublication?: boolean;
  confirmationDate?: string;
};

export type ContactChannel = {
  _type: "contactChannel";
  label: string;
  channelType: "phone" | "email" | "website" | "other";
  value: string;
  description?: string;
  authorizedForPublication?: boolean;
};

export type SocialLink = {
  _type: "socialLink";
  platform: "facebook" | "instagram" | "youtube" | "linkedin" | "x" | "other";
  label?: string;
  url: string;
};

export type Statistic = {
  _type: "statistic";
  kind: "firefighters" | "vehicles" | "availability" | "foundingYear" | "other";
  label: string;
  value: string;
  suffix?: string;
  confirmedForPublication?: boolean;
  asOfDate?: string;
  sourceNote?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Partner
  | SanityImageAssetReference
  | AccessibleImage
  | GoverningBody
  | InstitutionalDocumentReference
  | PortableText
  | SanityFileAssetReference
  | InstitutionalDocument
  | Gallery
  | Seo
  | Slug
  | Training
  | TrainingInformation
  | Vehicle
  | Service
  | NewsCategory
  | NewsCategoryReference
  | PersonReference
  | NewsArticle
  | InstitutionalPage
  | ContactInformation
  | Address
  | DonationInformation
  | MembershipInformation
  | RecruitmentInformation
  | ServiceReference
  | Homepage
  | CallToAction
  | SiteSettings
  | FaqItem
  | GalleryItem
  | GoverningRole
  | Person
  | DonationMethod
  | ContactChannel
  | SocialLink
  | Statistic
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries/contact.ts
// Variable: CONTACT_INFORMATION_QUERY
// Query: *[    _type == "contactInformation" &&    _id == "contactInformation" &&    informationConfirmedForPublication == true  ][0]{    _id,    address,    generalEmail,    telephone,    additionalChannels[authorizedForPublication == true]{      _key,      label,      channelType,      value,      description    },    contactHours,    directionsMapUrl,    socialLinks[]{_key, platform, label, url},    emergencyWarning,    seo  }
export type CONTACT_INFORMATION_QUERY_RESULT = {
  _id: "contactInformation";
  address: Address | null;
  generalEmail: string | null;
  telephone: string | null;
  additionalChannels: Array<{
    _key: string;
    label: string;
    channelType: "email" | "other" | "phone" | "website";
    value: string;
    description: string | null;
  }> | null;
  contactHours: PortableText | null;
  directionsMapUrl: string | null;
  socialLinks: Array<{
    _key: string;
    platform: "facebook" | "instagram" | "linkedin" | "other" | "x" | "youtube";
    label: string | null;
    url: string;
  }> | null;
  emergencyWarning: string;
  seo: Seo | null;
} | null;

// Source: ../web/src/sanity/queries/donations.ts
// Variable: DONATION_INFORMATION_QUERY
// Query: *[_type == "donationInformation" && _id == "donationInformation"][0]{    _id,    introduction,    waysToContribute,    donationMethods[confirmedForPublication == true]{      _key,      methodType,      title,      description,      iban,      mbWayNumber,      externalUrl    },    seo  }
export type DONATION_INFORMATION_QUERY_RESULT = {
  _id: "donationInformation";
  introduction: PortableText;
  waysToContribute: PortableText | null;
  donationMethods: Array<{
    _key: string;
    methodType: "bankTransfer" | "external" | "inPerson" | "mbWay" | "other";
    title: string;
    description: PortableText | null;
    iban: string | null;
    mbWayNumber: string | null;
    externalUrl: string | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: ../web/src/sanity/queries/galleries.ts
// Variable: GALLERIES_QUERY
// Query: *[_type == "gallery"] | order(date desc, title asc){    _id,    title,    "slug": slug.current,    date,    coverImage{      asset->{_id, url, metadata{dimensions, lqip}},      alt,      decorative,      caption,      credit,      crop,      hotspot    }  }
export type GALLERIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  date: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    decorative: boolean | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
}>;

// Source: ../web/src/sanity/queries/galleries.ts
// Variable: GALLERY_BY_SLUG_QUERY
// Query: *[_type == "gallery" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    date,    description,    coverImage{      asset->{_id, url, metadata{dimensions, lqip}},      alt,      decorative,      caption,      credit,      crop,      hotspot    },    items[]{      _key,      image{        asset->{_id, url, metadata{dimensions, lqip}},        alt,        decorative,        caption,        credit,        crop,        hotspot      }    },    seo  }
export type GALLERY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  date: string | null;
  description: PortableText | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    decorative: boolean | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  items: Array<{
    _key: string;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      decorative: boolean | null;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    };
  }>;
  seo: Seo | null;
} | null;

// Source: ../web/src/sanity/queries/governance.ts
// Variable: GOVERNING_BODIES_QUERY
// Query: *[_type == "governingBody"] | order(mandateStart desc, title asc){    _id,    bodyType,    title,    mandateStart,    mandateEnd,    description,    roles[]{      _key,      roleTitle,      publicNote,      person->{        _id,        publicName,        photograph{          asset->{_id, url, metadata{dimensions, lqip}},          alt,          decorative,          caption,          credit,          crop,          hotspot        },        biography,        publicContactChannels[authorizedForPublication == true]{          _key,          label,          channelType,          value,          description        }      }    }  }
export type GOVERNING_BODIES_QUERY_RESULT = Array<{
  _id: string;
  bodyType: "command" | "governingBody";
  title: string;
  mandateStart: string | null;
  mandateEnd: string | null;
  description: PortableText | null;
  roles: Array<{
    _key: string;
    roleTitle: string;
    publicNote: string | null;
    person: {
      _id: string;
      publicName: string;
      photograph: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            dimensions: SanityImageDimensions | null;
            lqip: string | null;
          } | null;
        } | null;
        alt: string | null;
        decorative: boolean | null;
        caption: string | null;
        credit: string | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
      } | null;
      biography: PortableText | null;
      publicContactChannels: Array<{
        _key: string;
        label: string;
        channelType: "email" | "other" | "phone" | "website";
        value: string;
        description: string | null;
      }> | null;
    };
  }>;
}>;

// Source: ../web/src/sanity/queries/governance.ts
// Variable: PEOPLE_QUERY
// Query: *[_type == "person"] | order(publicName asc){    _id,    publicName,    photograph{      asset->{_id, url, metadata{dimensions, lqip}},      alt,      decorative,      caption,      credit,      crop,      hotspot    },    biography,    publicContactChannels[authorizedForPublication == true]{      _key,      label,      channelType,      value,      description    }  }
export type PEOPLE_QUERY_RESULT = Array<{
  _id: string;
  publicName: string;
  photograph: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    decorative: boolean | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  biography: PortableText | null;
  publicContactChannels: Array<{
    _key: string;
    label: string;
    channelType: "email" | "other" | "phone" | "website";
    value: string;
    description: string | null;
  }> | null;
}>;

// Source: ../web/src/sanity/queries/homepage.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage" && _id == "homepage"][0]{    _id,    _type,    hero{      headline,      highlightedFragment,      description,      image{        asset->{_id, url, metadata{dimensions, lqip}},        alt,        decorative,        caption,        credit,        crop,        hotspot      },      emergencyCta,      recruitmentCta,      supportCta    },    statistics[confirmedForPublication == true]{      _key,      kind,      label,      value,      suffix,      asOfDate    },    mission{      sectionLabel,      title,      body,      image{        asset->{_id, url, metadata{dimensions, lqip}},        alt,        decorative,        caption,        credit,        crop,        hotspot      }    },    featuredServices[]->{      _id,      title,      "slug": slug.current,      summary,      visualType,      image{        asset->{_id, url, metadata{dimensions, lqip}},        alt,        decorative,        caption,        credit,        crop,        hotspot      },      icon    },    latestNews{sectionLabel, title, itemCount},    supportSection{sectionLabel, title, description, cta},    seo  }
export type HOMEPAGE_QUERY_RESULT = {
  _id: "homepage";
  _type: "homepage";
  hero: {
    headline: string;
    highlightedFragment: string | null;
    description: string | null;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      decorative: boolean | null;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    emergencyCta: CallToAction | null;
    recruitmentCta: CallToAction | null;
    supportCta: CallToAction | null;
  } | null;
  statistics: Array<{
    _key: string;
    kind:
      "availability" | "firefighters" | "foundingYear" | "other" | "vehicles";
    label: string;
    value: string;
    suffix: string | null;
    asOfDate: string | null;
  }> | null;
  mission: {
    sectionLabel: string | null;
    title: string | null;
    body: PortableText | null;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      decorative: boolean | null;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
  featuredServices: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    visualType: "icon" | "image";
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      decorative: boolean | null;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    icon:
      | "community"
      | "emergency"
      | "general"
      | "prevention"
      | "training"
      | "transport"
      | null;
  }> | null;
  latestNews: {
    sectionLabel: string | null;
    title: string | null;
    itemCount: number | null;
  } | null;
  supportSection: {
    sectionLabel: string | null;
    title: string | null;
    description: string | null;
    cta: CallToAction | null;
  } | null;
  seo: Seo | null;
} | null;

// Source: ../web/src/sanity/queries/institutional-documents.ts
// Variable: INSTITUTIONAL_DOCUMENTS_QUERY
// Query: *[_type == "institutionalDocument"] | order(date desc, title asc){    _id,    title,    category,    date,    reference,    accessibleSummary,    "file": file.asset->{_id, url, originalFilename, mimeType, size}  }
export type INSTITUTIONAL_DOCUMENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  category:
    "accounts" | "minutes" | "other" | "regulations" | "reports" | "statutes";
  date: string | null;
  reference: string | null;
  accessibleSummary: PortableText;
  file: {
    _id: string;
    url: string;
    originalFilename: string | null;
    mimeType: string;
    size: number;
  } | null;
}>;

// Source: ../web/src/sanity/queries/institutional-pages.ts
// Variable: INSTITUTIONAL_PAGE_QUERY
// Query: *[_type == "institutionalPage" && _id == $documentId][0]{    _id,    title,    introduction,    featuredImage{      asset->{_id, url, metadata{dimensions, lqip}},      alt,      decorative,      caption,      credit,      crop,      hotspot    },    body,    documents[]->{      _id,      title,      category,      date,      reference,      accessibleSummary,      "file": file.asset->{_id, url, originalFilename, mimeType, size}    },    seo  }
export type INSTITUTIONAL_PAGE_QUERY_RESULT = {
  _id: string;
  title: string;
  introduction: string | null;
  featuredImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    decorative: boolean | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  body: PortableText;
  documents: Array<{
    _id: string;
    title: string;
    category:
      "accounts" | "minutes" | "other" | "regulations" | "reports" | "statutes";
    date: string | null;
    reference: string | null;
    accessibleSummary: PortableText;
    file: {
      _id: string;
      url: string;
      originalFilename: string | null;
      mimeType: string;
      size: number;
    } | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: ../web/src/sanity/queries/membership.ts
// Variable: MEMBERSHIP_INFORMATION_QUERY
// Query: *[_type == "membershipInformation" && _id == "membershipInformation"][0]{    _id,    introduction,    eligibility,    benefits,    process[]{_key, title, description},    "fees": select(feesConfirmedForPublication == true => fees),    faq[]{_key, question, answer},    futureFormIntroduction,    seo  }
export type MEMBERSHIP_INFORMATION_QUERY_RESULT = {
  _id: "membershipInformation";
  introduction: PortableText;
  eligibility: PortableText | null;
  benefits: Array<string> | null;
  process: Array<{
    _key: string;
    title: string;
    description: string | null;
  }> | null;
  fees: PortableText | null;
  faq: Array<{
    _key: string;
    question: string;
    answer: PortableText;
  }> | null;
  futureFormIntroduction: PortableText | null;
  seo: Seo | null;
} | null;

// Source: ../web/src/sanity/queries/news.ts
// Variable: NEWS_ARTICLES_QUERY
// Query: *[_type == "newsArticle" && publicationDate <= now()]    | order(publicationDate desc) [0...$limit]{      _id,      title,      "slug": slug.current,      excerpt,      publicationDate,      fallbackVisual,      mainImage{        asset->{_id, url, metadata{dimensions, lqip}},        alt,        decorative,        caption,        credit,        crop,        hotspot      },      categories[]->{_id, name, "slug": slug.current}    }
export type NEWS_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publicationDate: string;
  fallbackVisual:
    | "community"
    | "fire"
    | "general"
    | "institutional"
    | "training"
    | "transport"
    | "vehicle"
    | null;
  mainImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    decorative: boolean | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  categories: Array<{
    _id: string;
    name: string;
    slug: string;
  }>;
}>;

// Source: ../web/src/sanity/queries/news.ts
// Variable: NEWS_ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "newsArticle" && slug.current == $slug && publicationDate <= now()][0]{    _id,    title,    "slug": slug.current,    excerpt,    publicationDate,    fallbackVisual,    mainImage{      asset->{_id, url, metadata{dimensions, lqip}},      alt,      decorative,      caption,      credit,      crop,      hotspot    },    body,    categories[]->{_id, name, "slug": slug.current},    author->{      _id,      publicName,      photograph{        asset->{_id, url, metadata{dimensions, lqip}},        alt,        decorative,        caption,        credit,        crop,        hotspot      }    },    seo  }
export type NEWS_ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publicationDate: string;
  fallbackVisual:
    | "community"
    | "fire"
    | "general"
    | "institutional"
    | "training"
    | "transport"
    | "vehicle"
    | null;
  mainImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    decorative: boolean | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  body: PortableText;
  categories: Array<{
    _id: string;
    name: string;
    slug: string;
  }>;
  author: {
    _id: string;
    publicName: string;
    photograph: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      decorative: boolean | null;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
  seo: Seo | null;
} | null;

// Source: ../web/src/sanity/queries/news.ts
// Variable: NEWS_CATEGORIES_QUERY
// Query: *[_type == "newsCategory"] | order(name asc){    _id,    name,    "slug": slug.current,    description  }
export type NEWS_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  description: string | null;
}>;

// Source: ../web/src/sanity/queries/partners.ts
// Variable: PARTNERS_QUERY
// Query: *[_type == "partner" && active == true]    | order(coalesce(displayOrder, 9999) asc, name asc){      _id,      name,      logo{        asset->{_id, url, metadata{dimensions, lqip}},        alt,        decorative,        caption,        credit,        crop,        hotspot      },      website,      description,      displayOrder    }
export type PARTNERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  logo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    decorative: boolean | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  website: string | null;
  description: string | null;
  displayOrder: number | null;
}>;

// Source: ../web/src/sanity/queries/recruitment.ts
// Variable: RECRUITMENT_INFORMATION_QUERY
// Query: *[_type == "recruitmentInformation" && _id == "recruitmentInformation"][0]{    _id,    introduction,    eligibility,    requirements,    stages[]{_key, title, description},    expectations,    faq[]{_key, question, answer},    futureFormIntroduction,    privacySummary,    seo  }
export type RECRUITMENT_INFORMATION_QUERY_RESULT = {
  _id: "recruitmentInformation";
  introduction: PortableText;
  eligibility: PortableText | null;
  requirements: Array<string> | null;
  stages: Array<{
    _key: string;
    title: string;
    description: string | null;
  }> | null;
  expectations: PortableText | null;
  faq: Array<{
    _key: string;
    question: string;
    answer: PortableText;
  }> | null;
  futureFormIntroduction: PortableText | null;
  privacySummary: PortableText | null;
  seo: Seo | null;
} | null;

// Source: ../web/src/sanity/queries/services.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(coalesce(displayOrder, 9999) asc, title asc){    _id,    title,    "slug": slug.current,    summary,    visualType,    image{      asset->{_id, url, metadata{dimensions, lqip}},      alt,      decorative,      caption,      credit,      crop,      hotspot    },    icon,    displayOrder  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  visualType: "icon" | "image";
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    decorative: boolean | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  icon:
    | "community"
    | "emergency"
    | "general"
    | "prevention"
    | "training"
    | "transport"
    | null;
  displayOrder: number | null;
}>;

// Source: ../web/src/sanity/queries/services.ts
// Variable: SERVICE_BY_SLUG_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    summary,    visualType,    image{      asset->{_id, url, metadata{dimensions, lqip}},      alt,      decorative,      caption,      credit,      crop,      hotspot    },    icon,    content,    availabilityInformation,    contactChannels[authorizedForPublication == true]{      _key,      label,      channelType,      value,      description    },    seo  }
export type SERVICE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  visualType: "icon" | "image";
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    decorative: boolean | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  icon:
    | "community"
    | "emergency"
    | "general"
    | "prevention"
    | "training"
    | "transport"
    | null;
  content: PortableText;
  availabilityInformation: PortableText | null;
  contactChannels: Array<{
    _key: string;
    label: string;
    channelType: "email" | "other" | "phone" | "website";
    value: string;
    description: string | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: ../web/src/sanity/queries/site-settings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    _id,    _type,    officialName,    shortName,    institutionalDescription,    logo{      asset->{        _id,        url,        metadata{dimensions, lqip}      },      alt,      decorative,      caption,      credit,      crop,      hotspot    },    siteUrl,    defaultSeo{      metaTitle,      metaDescription,      noIndex,      openGraphImage{        asset->{_id, url, metadata{dimensions, lqip}},        alt,        decorative,        caption,        credit,        crop,        hotspot      }    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  _type: "siteSettings";
  officialName: string;
  shortName: string | null;
  institutionalDescription: string | null;
  logo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    decorative: boolean | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  siteUrl: string | null;
  defaultSeo: {
    metaTitle: string | null;
    metaDescription: string | null;
    noIndex: boolean | null;
    openGraphImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      decorative: boolean | null;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries/training.ts
// Variable: TRAINING_INFORMATION_QUERY
// Query: *[_type == "trainingInformation" && _id == "trainingInformation"][0]{    _id,    introduction,    body,    seo  }
export type TRAINING_INFORMATION_QUERY_RESULT = {
  _id: "trainingInformation";
  introduction: PortableText;
  body: PortableText | null;
  seo: Seo | null;
} | null;

// Source: ../web/src/sanity/queries/training.ts
// Variable: TRAINING_QUERY
// Query: *[_type == "training"] | order(coalesce(startDate, "9999-12-31T23:59:59Z") asc, title asc){    _id,    title,    "slug": slug.current,    summary,    description,    startDate,    endDate,    location,    audience,    enrollmentInformation,    status,    seo  }
export type TRAINING_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  description: PortableText;
  startDate: string | null;
  endDate: string | null;
  location: string | null;
  audience: string | null;
  enrollmentInformation: PortableText | null;
  status: "cancelled" | "closed" | "completed" | "open" | "planned";
  seo: Seo | null;
}>;

// Source: ../web/src/sanity/queries/training.ts
// Variable: TRAINING_BY_SLUG_QUERY
// Query: *[_type == "training" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    summary,    description,    startDate,    endDate,    location,    audience,    enrollmentInformation,    status,    seo  }
export type TRAINING_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  description: PortableText;
  startDate: string | null;
  endDate: string | null;
  location: string | null;
  audience: string | null;
  enrollmentInformation: PortableText | null;
  status: "cancelled" | "closed" | "completed" | "open" | "planned";
  seo: Seo | null;
} | null;

// Source: ../web/src/sanity/queries/vehicles.ts
// Variable: VEHICLES_QUERY
// Query: *[_type == "vehicle"] | order(coalesce(displayOrder, 9999) asc, designation asc){    _id,    designation,    category,    otherCategory,    mainImage{      asset->{_id, url, metadata{dimensions, lqip}},      alt,      decorative,      caption,      credit,      crop,      hotspot    },    publicDescription,    "publicSpecifications": select(      specificationsApprovedForPublication == true => publicSpecifications    ),    gallery[]{      _key,      image{        asset->{_id, url, metadata{dimensions, lqip}},        alt,        decorative,        caption,        credit,        crop,        hotspot      }    },    displayOrder  }
export type VEHICLES_QUERY_RESULT = Array<{
  _id: string;
  designation: string;
  category: "ambulance" | "command" | "firefighting" | "other" | "support";
  otherCategory: string | null;
  mainImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    decorative: boolean | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  publicDescription: PortableText | null;
  publicSpecifications: Array<{
    label: string;
    value: string;
    _type: "publicSpecification";
    _key: string;
  }> | null;
  gallery: Array<{
    _key: string;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      decorative: boolean | null;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    };
  }> | null;
  displayOrder: number | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[\n    _type == "contactInformation" &&\n    _id == "contactInformation" &&\n    informationConfirmedForPublication == true\n  ][0]{\n    _id,\n    address,\n    generalEmail,\n    telephone,\n    additionalChannels[authorizedForPublication == true]{\n      _key,\n      label,\n      channelType,\n      value,\n      description\n    },\n    contactHours,\n    directionsMapUrl,\n    socialLinks[]{_key, platform, label, url},\n    emergencyWarning,\n    seo\n  }\n': CONTACT_INFORMATION_QUERY_RESULT;
    '\n  *[_type == "donationInformation" && _id == "donationInformation"][0]{\n    _id,\n    introduction,\n    waysToContribute,\n    donationMethods[confirmedForPublication == true]{\n      _key,\n      methodType,\n      title,\n      description,\n      iban,\n      mbWayNumber,\n      externalUrl\n    },\n    seo\n  }\n': DONATION_INFORMATION_QUERY_RESULT;
    '\n  *[_type == "gallery"] | order(date desc, title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    coverImage{\n      asset->{_id, url, metadata{dimensions, lqip}},\n      alt,\n      decorative,\n      caption,\n      credit,\n      crop,\n      hotspot\n    }\n  }\n': GALLERIES_QUERY_RESULT;
    '\n  *[_type == "gallery" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    description,\n    coverImage{\n      asset->{_id, url, metadata{dimensions, lqip}},\n      alt,\n      decorative,\n      caption,\n      credit,\n      crop,\n      hotspot\n    },\n    items[]{\n      _key,\n      image{\n        asset->{_id, url, metadata{dimensions, lqip}},\n        alt,\n        decorative,\n        caption,\n        credit,\n        crop,\n        hotspot\n      }\n    },\n    seo\n  }\n': GALLERY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "governingBody"] | order(mandateStart desc, title asc){\n    _id,\n    bodyType,\n    title,\n    mandateStart,\n    mandateEnd,\n    description,\n    roles[]{\n      _key,\n      roleTitle,\n      publicNote,\n      person->{\n        _id,\n        publicName,\n        photograph{\n          asset->{_id, url, metadata{dimensions, lqip}},\n          alt,\n          decorative,\n          caption,\n          credit,\n          crop,\n          hotspot\n        },\n        biography,\n        publicContactChannels[authorizedForPublication == true]{\n          _key,\n          label,\n          channelType,\n          value,\n          description\n        }\n      }\n    }\n  }\n': GOVERNING_BODIES_QUERY_RESULT;
    '\n  *[_type == "person"] | order(publicName asc){\n    _id,\n    publicName,\n    photograph{\n      asset->{_id, url, metadata{dimensions, lqip}},\n      alt,\n      decorative,\n      caption,\n      credit,\n      crop,\n      hotspot\n    },\n    biography,\n    publicContactChannels[authorizedForPublication == true]{\n      _key,\n      label,\n      channelType,\n      value,\n      description\n    }\n  }\n': PEOPLE_QUERY_RESULT;
    '\n  *[_type == "homepage" && _id == "homepage"][0]{\n    _id,\n    _type,\n    hero{\n      headline,\n      highlightedFragment,\n      description,\n      image{\n        asset->{_id, url, metadata{dimensions, lqip}},\n        alt,\n        decorative,\n        caption,\n        credit,\n        crop,\n        hotspot\n      },\n      emergencyCta,\n      recruitmentCta,\n      supportCta\n    },\n    statistics[confirmedForPublication == true]{\n      _key,\n      kind,\n      label,\n      value,\n      suffix,\n      asOfDate\n    },\n    mission{\n      sectionLabel,\n      title,\n      body,\n      image{\n        asset->{_id, url, metadata{dimensions, lqip}},\n        alt,\n        decorative,\n        caption,\n        credit,\n        crop,\n        hotspot\n      }\n    },\n    featuredServices[]->{\n      _id,\n      title,\n      "slug": slug.current,\n      summary,\n      visualType,\n      image{\n        asset->{_id, url, metadata{dimensions, lqip}},\n        alt,\n        decorative,\n        caption,\n        credit,\n        crop,\n        hotspot\n      },\n      icon\n    },\n    latestNews{sectionLabel, title, itemCount},\n    supportSection{sectionLabel, title, description, cta},\n    seo\n  }\n': HOMEPAGE_QUERY_RESULT;
    '\n  *[_type == "institutionalDocument"] | order(date desc, title asc){\n    _id,\n    title,\n    category,\n    date,\n    reference,\n    accessibleSummary,\n    "file": file.asset->{_id, url, originalFilename, mimeType, size}\n  }\n': INSTITUTIONAL_DOCUMENTS_QUERY_RESULT;
    '\n  *[_type == "institutionalPage" && _id == $documentId][0]{\n    _id,\n    title,\n    introduction,\n    featuredImage{\n      asset->{_id, url, metadata{dimensions, lqip}},\n      alt,\n      decorative,\n      caption,\n      credit,\n      crop,\n      hotspot\n    },\n    body,\n    documents[]->{\n      _id,\n      title,\n      category,\n      date,\n      reference,\n      accessibleSummary,\n      "file": file.asset->{_id, url, originalFilename, mimeType, size}\n    },\n    seo\n  }\n': INSTITUTIONAL_PAGE_QUERY_RESULT;
    '\n  *[_type == "membershipInformation" && _id == "membershipInformation"][0]{\n    _id,\n    introduction,\n    eligibility,\n    benefits,\n    process[]{_key, title, description},\n    "fees": select(feesConfirmedForPublication == true => fees),\n    faq[]{_key, question, answer},\n    futureFormIntroduction,\n    seo\n  }\n': MEMBERSHIP_INFORMATION_QUERY_RESULT;
    '\n  *[_type == "newsArticle" && publicationDate <= now()]\n    | order(publicationDate desc) [0...$limit]{\n      _id,\n      title,\n      "slug": slug.current,\n      excerpt,\n      publicationDate,\n      fallbackVisual,\n      mainImage{\n        asset->{_id, url, metadata{dimensions, lqip}},\n        alt,\n        decorative,\n        caption,\n        credit,\n        crop,\n        hotspot\n      },\n      categories[]->{_id, name, "slug": slug.current}\n    }\n': NEWS_ARTICLES_QUERY_RESULT;
    '\n  *[_type == "newsArticle" && slug.current == $slug && publicationDate <= now()][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publicationDate,\n    fallbackVisual,\n    mainImage{\n      asset->{_id, url, metadata{dimensions, lqip}},\n      alt,\n      decorative,\n      caption,\n      credit,\n      crop,\n      hotspot\n    },\n    body,\n    categories[]->{_id, name, "slug": slug.current},\n    author->{\n      _id,\n      publicName,\n      photograph{\n        asset->{_id, url, metadata{dimensions, lqip}},\n        alt,\n        decorative,\n        caption,\n        credit,\n        crop,\n        hotspot\n      }\n    },\n    seo\n  }\n': NEWS_ARTICLE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "newsCategory"] | order(name asc){\n    _id,\n    name,\n    "slug": slug.current,\n    description\n  }\n': NEWS_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "partner" && active == true]\n    | order(coalesce(displayOrder, 9999) asc, name asc){\n      _id,\n      name,\n      logo{\n        asset->{_id, url, metadata{dimensions, lqip}},\n        alt,\n        decorative,\n        caption,\n        credit,\n        crop,\n        hotspot\n      },\n      website,\n      description,\n      displayOrder\n    }\n': PARTNERS_QUERY_RESULT;
    '\n  *[_type == "recruitmentInformation" && _id == "recruitmentInformation"][0]{\n    _id,\n    introduction,\n    eligibility,\n    requirements,\n    stages[]{_key, title, description},\n    expectations,\n    faq[]{_key, question, answer},\n    futureFormIntroduction,\n    privacySummary,\n    seo\n  }\n': RECRUITMENT_INFORMATION_QUERY_RESULT;
    '\n  *[_type == "service"] | order(coalesce(displayOrder, 9999) asc, title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    visualType,\n    image{\n      asset->{_id, url, metadata{dimensions, lqip}},\n      alt,\n      decorative,\n      caption,\n      credit,\n      crop,\n      hotspot\n    },\n    icon,\n    displayOrder\n  }\n': SERVICES_QUERY_RESULT;
    '\n  *[_type == "service" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    visualType,\n    image{\n      asset->{_id, url, metadata{dimensions, lqip}},\n      alt,\n      decorative,\n      caption,\n      credit,\n      crop,\n      hotspot\n    },\n    icon,\n    content,\n    availabilityInformation,\n    contactChannels[authorizedForPublication == true]{\n      _key,\n      label,\n      channelType,\n      value,\n      description\n    },\n    seo\n  }\n': SERVICE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    _id,\n    _type,\n    officialName,\n    shortName,\n    institutionalDescription,\n    logo{\n      asset->{\n        _id,\n        url,\n        metadata{dimensions, lqip}\n      },\n      alt,\n      decorative,\n      caption,\n      credit,\n      crop,\n      hotspot\n    },\n    siteUrl,\n    defaultSeo{\n      metaTitle,\n      metaDescription,\n      noIndex,\n      openGraphImage{\n        asset->{_id, url, metadata{dimensions, lqip}},\n        alt,\n        decorative,\n        caption,\n        credit,\n        crop,\n        hotspot\n      }\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "trainingInformation" && _id == "trainingInformation"][0]{\n    _id,\n    introduction,\n    body,\n    seo\n  }\n': TRAINING_INFORMATION_QUERY_RESULT;
    '\n  *[_type == "training"] | order(coalesce(startDate, "9999-12-31T23:59:59Z") asc, title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    description,\n    startDate,\n    endDate,\n    location,\n    audience,\n    enrollmentInformation,\n    status,\n    seo\n  }\n': TRAINING_QUERY_RESULT;
    '\n  *[_type == "training" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    description,\n    startDate,\n    endDate,\n    location,\n    audience,\n    enrollmentInformation,\n    status,\n    seo\n  }\n': TRAINING_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "vehicle"] | order(coalesce(displayOrder, 9999) asc, designation asc){\n    _id,\n    designation,\n    category,\n    otherCategory,\n    mainImage{\n      asset->{_id, url, metadata{dimensions, lqip}},\n      alt,\n      decorative,\n      caption,\n      credit,\n      crop,\n      hotspot\n    },\n    publicDescription,\n    "publicSpecifications": select(\n      specificationsApprovedForPublication == true => publicSpecifications\n    ),\n    gallery[]{\n      _key,\n      image{\n        asset->{_id, url, metadata{dimensions, lqip}},\n        alt,\n        decorative,\n        caption,\n        credit,\n        crop,\n        hotspot\n      }\n    },\n    displayOrder\n  }\n': VEHICLES_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
